<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * @file
 * Primary module hooks for EWP Institutions User bridge module.
 */

/**
 * Implements hook_entity_base_field_info().
 */
function ewp_institutions_user_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'user') {

    $fields['user_institution'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Institution'))
      ->setDescription(t('The Institution with which the User is associated.'))
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setRequired(FALSE)
      ->setSetting('handler', 'default:hei')
      ->setSetting('target_type', 'hei')
      ->setSetting('handler_settings', [
        'auto_create' => TRUE,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => 60,
          'placeholder' => '',
        ],
        'weight' => 20,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'above',
        'type' => 'string',
        'weight' => 20,
      ])
      ->setDisplayConfigurable('view', TRUE);

    return $fields;
  }
}
