<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for EWP Institutions User bridge module.
 */

/**
 * Implements hook_entity_base_field_info().
 */
function ewp_institutions_user_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'user') {
    $bridge = \Drupal::service('ewp_institutions_user.bridge');
    return $bridge->attachBaseField();
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ewp_institutions_user_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $bridge = \Drupal::service('ewp_institutions_user.bridge');
  $bridge->userFormAlter($form, $form_state);
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function ewp_institutions_user_field_widget_complete_entity_reference_autocomplete_form_alter(array &$elements, FormStateInterface $form_state, array $context) {
  $bridge = \Drupal::service('ewp_institutions_user.bridge');
  $bridge->autocompleteAlter($elements, $form_state, $context);
}
