<?php

/**
 * @file
 * Contains ewp_institutions_ref.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_help().
 */
function ewp_institutions_ref_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ewp_institutions_ref module.
    case 'help.page.ewp_institutions_ref':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Improvements to Institution Entity Reference') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function ewp_institutions_ref_form_alter(&$form, FormStateInterface $form_state) {
  // dpm($form);
}
