<?php

/**
 * @file
 * Contains ewp_institutions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ewp_institutions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ewp_institutions module.
    case 'help.page.ewp_institutions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal implementation of the EWP Institutions API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ewp_institutions_theme() {
  return [
    'ewp_contact' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ewp_institutions_theme_suggestions_org(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#hei'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'hei__' . $sanitized_view_mode;
  $suggestions[] = 'hei__' . $entity->id();
  $suggestions[] = 'hei__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function ewp_institutions_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type === 'hei') {
    if (isset($fields['hei_id'])) {
      $fields['hei_id']->addConstraint('UniqueField', []);
    }
  }
}

/**
 * Get Other ID types.
 *
 * Get associative array of Other HEI identifier types from a source file.
 *
 * @return array $options
 */
function ewp_institutions_get_other_id_types() {
  $source_file = 'other_id_types.inc';
  include $source_file;

  $options = [];
  foreach ($other_id_types as $key => $value) {
    $options[$key] = $value;
  }

  return $options;
}
