ewp_institutions_get.settings:
  type: config_object
  label: 'External API settings'
  mapping:
    index_endpoint:
      type: text
      label: 'Index endpoint'

ewp_institutions_get.fieldmap:
  type: config_object
  label: 'Field mapping'
  mapping:
    field_mapping:
      type: sequence
      label: 'Entity fields'
      sequence:
        type: string

ewp_institutions_get.field_settings:
  type: config_object
  label: 'Field settings'
  mapping:
    field_exclude:
      type: sequence
      label: 'Entity fields to exclude from mapping'
      sequence:
        type: string
    remote_exclude:
      type: sequence
      label: 'Remote keys to exclude from mapping'
      sequence:
        type: string
    remote_include:
      type: sequence
      label: 'Remote keys to include in mapping'
      sequence:
        type: string
