ewp_institutions_get.settings:
  type: config_object
  label: 'External API settings'
  mapping:
    index_endpoint:
      type: text
      label: 'Index endpoint'

ewp_institutions_get.settings.fieldmap:
  type: config_object
  label: 'Field mapping'
  mapping:
    entity_type:
      type: string
      label: 'Entity type'
    entity_bundle:
      type: string
      label: 'Entity bundle'
    field_mapping:
      type: mapping
      label: 'Entity fields'
      mapping:
        label:
          type: string
          label: 'Label'
