ewp_institutions_get.settings:
  type: config_object
  label: 'External API settings'
  mapping:
    index_endpoint:
      type: uri
      label: 'Index endpoint'

ewp_institutions_get.fieldmap:
  type: config_object
  label: 'Field mapping'
  mapping:
    field_mapping:
      type: sequence
      label: 'Entity fields'
      constraints:
        FullyValidatable: ~
      sequence:
        type: machine_name

ewp_institutions_get.field_settings:
  type: config_object
  label: 'Field settings'
  mapping:
    field_exclude:
      type: sequence
      label: 'Entity fields to exclude from mapping'
      constraints:
        FullyValidatable: ~
      sequence:
        type: machine_name
    remote_exclude:
      type: sequence
      label: 'Remote keys to exclude from mapping'
      constraints:
        FullyValidatable: ~
      sequence:
        type: string
        constraints:
          Regex:
            pattern: /^[a-zA-Z0-9][a-zA-Z0-9_-]*[a-zA-Z0-9]$/
    remote_include:
      type: sequence
      label: 'Remote keys to include in mapping'
      constraints:
        FullyValidatable: ~
      sequence:
        type: string
        constraints:
          Regex:
            pattern: /^[a-zA-Z0-9][a-zA-Z0-9_-]*[a-zA-Z0-9]$/
# see https://jsonapi.org/format/#document-member-names-allowed-characters
