ewp_institutions_user.settings:
  type: config_object
  label: 'Institutions User bridge settings'
  mapping:
    cardinality:
      type: integer
      label: 'Allowed number of values'
    required:
      type: boolean
      label: 'Required field'
    auto_create:
      type: boolean
      label: "Create referenced entities if they don't already exist"
