ewp_institutions_user.settings:
  type: config_object
  label: 'Institutions User bridge settings'
  mapping:
    cardinality:
      type: integer
      label: 'Cardinality'
    required:
      type: boolean
      label: 'Required'
    auto_create:
      type: boolean
      label: 'Auto create'
